config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get /topics => topic/index

  resources :topics do
    resources :conversations
  end
  
  namespace 'admin' do
    resources :topics do
      resources :conversations
    end
  end
  # get /topics/:id/conversation => conversations/index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :conversations
end

app/controllers/admin/conversations_controller.rb
class Admin::ConversationsController < ApplicationController
  # do whatever you want in here
  def index
    topic_id = params['topic_id']
    # req.params.topic_id
    @topic = Topic.find(topic_id)

    # @conversations = Conversation.where(topic: @topic)
    @conversations = @topic.conversations

  end

  def destroy
    @conversation = Conversation.find(params[:id])

    @conversation.destroy

    redirect_to topics_path
  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  # do whatever you want in here
  def index
    @topics = Topic.all
    # implied that we call render on index, with some vars
  end

  def destroy
    @topic = Topic.find(params[:id])

    @topic.destroy

    redirect_to topics_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    topic_id = params['topic_id']
    # req.params.topic_id
    @topic = Topic.find(topic_id)

    # @conversations = Conversation.where(topic: @topic)
    @conversations = @topic.conversations


  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/conversations/index.html.erb
<h1>
  Conversations for <%= @topic.name %>!
</h1>
  <%= form_for :conversation, url: topic_conversations_path(@topic) do |f| %>
    <h2>New conversation</h2>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

    <%= f.submit("Create conversation") %><br>

  <% end %>

<ul>
  <% @conversations.each do |c| %>
    <li><%= c.title %></li>
    <%= button_to 'Delete', admin_topic_conversation_url(@topic, c), :method => :delete %>
  <% end %>

</ul>

app/views/admin/topics/index.html.erb
<h1>
  Topics! AS AN ADMIN!!!! ⚡️
</h1>
<ul>
  <% @topics.each do |topic| %>
    <li>
      <%= link_to topic.name, topic_conversations_url(topic) %>
      <img src="<%= topic.image %>" style="height: 150px" />
      <%= button_to 'Delete ' + topic.name, admin_topic_url(topic), :method => :delete %>
    </li>
  <% end %>
</ul>

app/views/conversations/index.html.erb
<h1>
  Conversations for <%= @topic.name %>!
</h1>
<ul>
  <% @conversations.each do |c| %>
    <li><%= c.title %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditBetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/index.html.erb
<h1>
  Topics!
</h1>
<ul>
  <% @topics.each do |topic| %>
    <li>
      <%= link_to topic.name, topic_conversations_url(topic) %>
      <img src="<%= topic.image %>" style="height: 150px" />
    </li>
  <% end %>
</ul>